import { StyleSheet } from "react-native";
import theme from "../theme/theme";

export default StyleSheet.create({
  content: {
    flexGrow: 1,
    paddingHorizontal: theme.spacing.lg,
    paddingTop: theme.spacing.lg,
    paddingBottom: theme.spacing.xl,
    gap: theme.spacing.lg,
  },
  stepWrap: {
    flex: 1,
    gap: theme.spacing.md,
  },
  backButton: {
    alignSelf: "flex-start",
    minHeight: theme.touch.minSize,
    justifyContent: "center",
    paddingHorizontal: theme.spacing.xs,
  },
  backText: {
    fontSize: theme.typography.sizes.h2,
    color: theme.colors.textPrimary,
    fontFamily: theme.typography.fontFamilyDisplay,
  },
  title: {
    color: theme.colors.textPrimary,
    lineHeight: 34,
  },
  subtitle: {
    color: theme.colors.textSecondary,
  },
  questionCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radii.lg,
    padding: theme.spacing.lg,
    gap: theme.spacing.sm,
  },
  questionLabel: {
    fontSize: theme.typography.sizes.small,
    color: theme.colors.muted,
    fontFamily: theme.typography.fontFamilyPrimary,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  questionText: {
    fontSize: theme.typography.sizes.h3,
    color: theme.colors.textPrimary,
    fontFamily: theme.typography.fontFamilyPrimary,
    lineHeight: 28,
    fontWeight: "600",
  },
  optionList: {
    gap: theme.spacing.sm,
  },
  optionButton: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radii.md,
    borderWidth: 1,
    borderColor: theme.colors.backgroundAlt,
    paddingHorizontal: theme.spacing.md,
    minHeight: 56,
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.sm,
  },
  optionButtonSelected: {
    borderWidth: 2,
    borderColor: theme.colors.primary,
    backgroundColor: theme.colors.cardSoft,
  },
  optionBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: theme.colors.backgroundAlt,
    alignItems: "center",
    justifyContent: "center",
  },
  optionBadgeText: {
    color: theme.colors.textPrimary,
    fontSize: theme.typography.sizes.small,
    fontFamily: theme.typography.fontFamilyDisplay,
    fontWeight: "700",
  },
  optionText: {
    color: theme.colors.textPrimary,
    fontSize: theme.typography.sizes.body,
    fontFamily: theme.typography.fontFamilyPrimary,
    fontWeight: "600",
    flex: 1,
  },
  scaleHint: {
    color: theme.colors.muted,
    fontSize: theme.typography.sizes.small,
    fontFamily: theme.typography.fontFamilyPrimary,
    lineHeight: 20,
    marginTop: theme.spacing.xs,
  },
  successWrap: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    gap: theme.spacing.md,
  },
  successTitle: {
    textAlign: "center",
  },
  successSubtitle: {
    textAlign: "center",
    color: theme.colors.textSecondary,
  },
  infoBox: {
    backgroundColor: theme.colors.backgroundAlt,
    borderRadius: theme.radii.md,
    padding: theme.spacing.md,
    width: "100%",
  },
  infoText: {
    textAlign: "center",
    color: theme.colors.textSecondary,
    lineHeight: 22,
  },
  alertBox: {
    backgroundColor: theme.colors.emergencySoft,
    borderRadius: theme.radii.md,
    borderWidth: 1,
    borderColor: theme.colors.danger,
    padding: theme.spacing.md,
    width: "100%",
  },
  alertText: {
    color: theme.colors.danger,
    textAlign: "center",
    fontSize: theme.typography.sizes.body,
    fontFamily: theme.typography.fontFamilyPrimary,
    lineHeight: 22,
    fontWeight: "600",
  },
  primaryButton: {
    borderRadius: theme.radii.pill,
    minHeight: 50,
    paddingHorizontal: theme.spacing.xl,
    backgroundColor: theme.colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButtonText: {
    color: theme.colors.white,
    fontFamily: theme.typography.fontFamilyDisplay,
    fontSize: theme.typography.sizes.body,
    fontWeight: "600",
  },
  ghostLink: {
    minHeight: theme.touch.minSize,
    justifyContent: "center",
  },
  ghostLinkText: {
    color: theme.colors.primary,
    fontSize: theme.typography.sizes.body,
    fontFamily: theme.typography.fontFamilyPrimary,
    fontWeight: "600",
  },
});
